- id: '1653403784211'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - device_id: 94835e85c2e4e51ba462015b78b1659b
    domain: deconz
    platform: device
    type: remote_button_rotated
    subtype: left
  condition: []
  action:
  - device_id: 6896dd9bceb131f61b6e36de1bf8355b
    domain: light
    entity_id: light.keuken
    type: brightness_decrease
  mode: single
- id: '1653406277407'
  alias: Lamp aan
  description: ''
  trigger:
  - device_id: 94835e85c2e4e51ba462015b78b1659b
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 6896dd9bceb131f61b6e36de1bf8355b
    entity_id: light.keuken
    domain: light
  mode: single
- id: '1653406389359'
  alias: Knop links
  description: ''
  trigger:
  - device_id: 94835e85c2e4e51ba462015b78b1659b
    domain: deconz
    platform: device
    type: remote_button_rotated
    subtype: left
  condition: []
  action:
  - device_id: 6896dd9bceb131f61b6e36de1bf8355b
    domain: light
    entity_id: light.keuken
    type: flash
  mode: single

