- id: '1652961017021'
  alias: Test
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action: []
  mode: single
- id: '1652961067081'
  alias: Schakel op tijd
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - device_id: 38ef84d35f9c12af4fbda8286d8c403a
    domain: fan
    entity_id: fan.eetkamer
    type: turn_on
  mode: single
