# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Change radius for home
homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: -1
  customize:
    zone.home:
      radius: 50
  packages: !include_dir_named include/intergrations


group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml
#switch: !include_dir_merge_list switches

automation: !include_dir_merge_list include/automations
climate: !include_dir_merge_list include/climate
sensor: !include_dir_merge_list include/sensors
binary_sensor: !include_dir_merge_list include/binary_sensor
media_player: !include_dir_merge_list include/media_player

frontend:
  themes: !include_dir_merge_named themes
